//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC2Scrapbook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SC2Scrapbook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bronze {
            get {
                object obj = ResourceManager.GetObject("bronze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Builds&gt;
        ///	&lt;Build&gt;
        ///		&lt;Build&gt;
        ///			&lt;Name&gt;
        ///				&lt;string&gt;Cloaked Banshee&lt;/string&gt;
        ///			&lt;/Name&gt;
        ///			&lt;Matchup&gt;
        ///				&lt;Matchup&gt;TvX&lt;/Matchup&gt;
        ///			&lt;/Matchup&gt;
        ///			&lt;Script&gt;
        ///				&lt;string&gt;10 - Depot [1]&amp;#xD;
        ///12 - Barracks [1]&amp;#xD;
        ///13 - Refinery [1] (Scout)&amp;#xD;
        ///15 - Orbital&amp;#xD;
        ///15 - Marine&amp;#xD;
        ///16 - Depot [2]&amp;#xD;
        ///17 - Factory&amp;#xD;
        ///18 - Refinery [2]&amp;#xD;
        ///#Hellion, Starport, Techlab Factory&amp;#xD;
        ///#Wall ramp with Bunker + 2 Depots&amp;#xD;
        ///#Switch Starport onto Techlab&amp;#xD;
        ///#Cloak before [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string builds {
            get {
                return ResourceManager.GetString("builds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0
        ///------------------
        ///New: Changed name to SC2 Scrapbook.
        ///New: Added build sharing capabilities via right-click. You can send other
        ///     SC2 Scrapbook users your builds by sending them the Sharecode generated
        ///     by the various sharing options.
        ///
        ///     SC2 Scrapbook registers the sc2bo:// protocol to handle Sharecodes.
        ///
        ///     Build Order Sharecodes are XML representations of the internal Build
        ///     object with GZip compression and base64 encoding.
        ///New: Added advanced SC2 interaction. These options [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap defaultportrait {
            get {
                object obj = ResourceManager.GetObject("defaultportrait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap diamond {
            get {
                object obj = ResourceManager.GetObject("diamond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gold {
            get {
                object obj = ResourceManager.GetObject("gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grandmaster {
            get {
                object obj = ResourceManager.GetObject("grandmaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap master {
            get {
                object obj = ResourceManager.GetObject("master", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap none {
            get {
                object obj = ResourceManager.GetObject("none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version =&quot;1.0&quot; encoding =&quot;utf-8&quot;?&gt;
        ///&lt;!-- R1CH&apos;s formatting was too simple not to steal, but I think siphoning his patch file bandwidth is a bit too far ;D --&gt;
        ///&lt;Patches&gt;
        ///	&lt;Patch Version=&quot;1.4.2&quot; Ptr1=&quot;026a6f08&quot; Ptr2=&quot;016c8878&quot; Size1=&quot;8d8&quot; Size2=&quot;4b0&quot; /&gt;
        ///&lt;/Patches&gt;.
        /// </summary>
        internal static string patch {
            get {
                return ResourceManager.GetString("patch", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap platinum {
            get {
                object obj = ResourceManager.GetObject("platinum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap portrait_summary {
            get {
                object obj = ResourceManager.GetObject("portrait_summary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap protoss {
            get {
                object obj = ResourceManager.GetObject("protoss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap protoss_gas {
            get {
                object obj = ResourceManager.GetObject("protoss_gas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap protoss_minerals {
            get {
                object obj = ResourceManager.GetObject("protoss_minerals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap protoss_supply {
            get {
                object obj = ResourceManager.GetObject("protoss_supply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap protoss_time {
            get {
                object obj = ResourceManager.GetObject("protoss_time", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProtossIcon {
            get {
                object obj = ResourceManager.GetObject("ProtossIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap random {
            get {
                object obj = ResourceManager.GetObject("random", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RandomIcon {
            get {
                object obj = ResourceManager.GetObject("RandomIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap silver {
            get {
                object obj = ResourceManager.GetObject("silver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap snapshot_protoss {
            get {
                object obj = ResourceManager.GetObject("snapshot_protoss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap snapshot_random {
            get {
                object obj = ResourceManager.GetObject("snapshot_random", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap snapshot_terran {
            get {
                object obj = ResourceManager.GetObject("snapshot_terran", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap snapshot_zerg {
            get {
                object obj = ResourceManager.GetObject("snapshot_zerg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap terran {
            get {
                object obj = ResourceManager.GetObject("terran", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap terran_gas {
            get {
                object obj = ResourceManager.GetObject("terran_gas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap terran_minerals {
            get {
                object obj = ResourceManager.GetObject("terran_minerals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap terran_supply {
            get {
                object obj = ResourceManager.GetObject("terran_supply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap terran_time {
            get {
                object obj = ResourceManager.GetObject("terran_time", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TerranIcon {
            get {
                object obj = ResourceManager.GetObject("TerranIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2|SC2 Scrapbook 1.0|http://www.teamliquid.net/forum/viewmessage.php?topic_id=252809.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap zerg {
            get {
                object obj = ResourceManager.GetObject("zerg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zerg_gas {
            get {
                object obj = ResourceManager.GetObject("zerg_gas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zerg_minerals {
            get {
                object obj = ResourceManager.GetObject("zerg_minerals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zerg_supply {
            get {
                object obj = ResourceManager.GetObject("zerg_supply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zerg_time {
            get {
                object obj = ResourceManager.GetObject("zerg_time", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zergicon {
            get {
                object obj = ResourceManager.GetObject("zergicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
